name: Stash-cache
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Updating PIP
        run: pip3 install --upgrade setuptools

      - name: Install packages
        run: pip3 install -r requirements.txt

      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run Tests
        run: pytest tests/test*

      - name: Install tox
        run: pip3 install tox

      - name: Run tox tests
        run: tox
